config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # verb 'path', to: 'controller#action'
  get '/tasks', to: 'tasks#index', as: "index"
  # new task
  get '/tasks/new', to: 'tasks#new', as: "new" # display the form
  # read all task
  get '/tasks/:id', to: 'tasks#show', as: "show"
  # create a task
  post '/tasks/', to: 'tasks#create'
  # update a task
  get '/tasks/:id/edit', to: 'tasks#edit', as: "edit"

  patch '/tasks/:id', to: 'tasks#update'
  # delete a task
  delete '/tasks/:id', to: 'tasks#destroy', as: "delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def new
    @task = Task.new
  end
  def show
    @task = Task.find(params[:id])
  end
  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to index_path
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    @task = update.(task_params)
    redirect_to show_path(t)
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed, {}, true, false %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks list 🚀</h1>
<%= link_to "Create a new task", new_path %>
<ul>
  <% @tasks.each do |t| %>
    <li><%= link_to t.title, show_path(t) %> - <%= t.completed %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed, {}, true, false %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task</h1>

<li><%= @task.title %> - <%= @task.details %> - <%= @task.completed %></li>
<%= link_to "Back", tasks_path %>
<%= link_to "Edit", edit_path(@task) %>
<%= link_to "Delete", delete_path(@task), method: :delete, data: { confirm: 'Are you sure?' } %>